# Generated by Django 5.0 on 2024-03-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleduty',
            name='duty',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roleduty',
            name='duty_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
