# Generated by Django 5.0.2 on 2024-02-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
