# Generated by Django 5.0 on 2024-03-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstatus',
            name='color',
        ),
    ]
