# Generated by Django 5.0 on 2024-03-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
                ('text_ar', models.CharField(default='', max_length=50)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Project Type',
                'verbose_name_plural': 'Project Type',
            },
        ),
    ]
