# Generated by Django 5.0 on 2024-03-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectstatus_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
