# Generated by Django 5.0 on 2024-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='text_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
