branch-defaults:
  main:
    environment: adm-pm
environment-defaults:
  ProjectManagement-dev:
    branch: null
    repository: null
global:
  application_name: ProjectManagement
  default_ec2_keyname: adm-prjmgmt-aws-eb-key
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: me-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
